import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/css/Home.module.css'

export default function Profile() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Profile Page
        </h1>
      </main>
    </div>
  )
}

export const ProfileID = function Profile(props) {
    let { id } = 12;

    return (
        <div className="Home">
            <Sidebar/>
            {/* Tinder Cards */ } 
            {/* Swipe Buttons Cards */ } 
            {/* Chat Screen */ } 
            {/* Individual Chat Screen */ } 
            <h1>Let's Build React Profile for Child ID: {props.match.params.id}!</h1>
        </div>
    );
}
